TestSAML(): do not use require.NotEmpty() when checking assertionInfo.WarningInfo
Provided there is no error returned by RetrieveAssertionInfo(),
assertionInfo.WarningInfo will be set.  The fields of WarningInfo may
have zero values, however.  require.NotEmpty() does different things
locally with go version 1.8 vs. travis go version 1.5.

running TestSAML() locally, assertionInfo.WarningInfo is not nil
and require.NotEmpty(assertionInfo.WarningInfo) passes.

With travis, require.NotEmpty(assertionInfo.WarningInfo) fails:

$ gimme version
v1.2.0
$ go version
go version go1.5 linux/amd64
...
--- FAIL: TestSAML (0.05s)
    Error Trace:   saml_test.go:98
    Error:         Should NOT be empty, but was &{false <nil> false false}

It appears that a deeper inspection is happening in the travis run
where the zero field values constitute the notion of 'empty'.

Replaced require.NotEmpty() with require.NotNil() and added
test for zero values on the individual fields.